[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-flat_gruvbox_dark
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-flat_gruvbox_dark
GtkTheme=oomox-flat_gruvbox_dark
IconTheme=oomox-flat_gruvbox_dark
MetacityTheme=oomox-flat_gruvbox_dark
