require('settings')
require('packer-config')
require('telescope').load_extension('media_files')
require('colorschemes-config.gruvbox')
require('nvim-tree-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.clangd-config')
require('nvim-cmp-config')
require('nvim-treesitter-config')
require('nvim-orgmode-config')
require('nvim-org-bullets-config')
require('nvim-zen-mode-config')
require('nvim-neorg-config')
require('nvim-barbar-config')
require('nvim-lualine-config')
require('nvim-notify-config')

